services:
    backend:
        build: backend
        ports:
            - '8000:8000'
    frontend:
        build: frontend
        ports:
            - '80:8000'
    db:
        image: mysql:latest
        ports:
            - '0.0.0.0:3307:3306'
        volumes:
            - ./init.sql:/db/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: run/secrets/mysql_root_password
            MYSQL_DATABASE: CreditDB
            MYSQL_USER: manager
            MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
        secrets:
            - mysql_password
            - mysql_root_password
secrets:
    mysql_password:
        file: ./db/password.txt
    mysql_root_password:
        file: ./db/root_password.txt
